default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Hirumi01

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_back_end_development

test:
  <<: *default
  database: hello_rails_back_end_test

production:
  <<: *default
  database: hello_rails_back_end_production
  username: hello_rails_back_end
  password: <%= ENV["HELLO_RAILS_BACK_END_DATABASE_PASSWORD"] %>
